name: BloodyNotes
main: xtcy\bn\Loader
api: 5.0.0
version: 2.0.0
author: xtcy_

depend:
  - BedrockEconomy

permissions:
  bloodynotes.command:
    default: op
  bloodynotes.command.give:
    default: op
